### ISSUE TITLE
Unable to push -> "Error: Repository cannot be found"

### ISSUE THREAD

**Issue by irischien** [comp426-2022-spring/a00#10]
Hi! I'm having trouble pushing the assignment 00 to Github. I have attached a screenshot of my terminal and the issue at hand. I should have the assignment completed, I am just having issues with submission. I've tried some solutions I found online, but none of them work. Thank you! 

![Screenshot (343)](https://user-images.githubusercontent.com/69520582/150015204-aa2cdc44-88d2-4bd1-a81e-282c73c25aa5.png)

**Comment by irischien** [comment]
**The exact error message is:** 
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by camsimba** [comment]
Hey, I'll see if I can help out some. Off the bat, I don't see anything wrong other than you didn't commit some changes after doing 'git add *', but you already have some commits pending so it shouldn't matter. You currently have collaborator access to your repo, which is correctly listed in your terminal (comp426-2022-spring/a00-irischien). The error leads me to believe that somehow git messed up the repository name when trying to push. 

Can you execute this command and tell me what it says -> 'git remote show origin'
This should show you both a fetch URL and a push URL, I'm thinking that maybe the push URL is messed up.

**Comment by irischien** [comment]
Hi! After git remote show origin, it gives me the same ERROR
![image](https://user-images.githubusercontent.com/69520582/150023292-1821fcaf-5978-4c82-beb4-0ea8265137d3.png)

**Comment by camsimba** [comment]
Maybe it is an issue with credentials then? Are you properly signed in to your github in that terminal? If, for some reason, you didn't have a SSH key assigned or a Personal Access Token that you are using to push/pull, then it would also give you this error. Do you remember the terminal ever asking you to sign in to your github account to then clone the repository?

**Comment by irischien** [comment]
I'm not sure how to properly sign in? I've never had an issue with it before...it has not asked me to sign into my GitHub account before I cloned the repository. I don't think I had an SSH key/Token I used to push and pull? Is there a way I can make a new key or token and then connect it? or if I can delete my work and reclone/start over? Thank you!

**Comment by camsimba** [comment]
@irischien I would try the steps I posted in comp426-2022-spring/a00#8 and see if it works after that, as this might be a similar issue. If it doesn't try troubleshooting it with the troubleshooting guide also linked in that issue. If it still doesn't work, let me know and we can think of some solutions or you can visit office hours and have somebody help you out there!
