### ISSUE TITLE
"remote: Invalid username or password. fatal: Authentication failed"

### ISSUE THREAD

**Issue by karengu0** [comp426-2022-spring/a00#12]
When I type "git push," my VSCode terminal displays that error. What do I do? I've staged everything.

**Comment by samrshi** [comment]
Hey Karen! When you do this, are you prompted to enter a username/password?

**Comment by samrshi** [comment]
> Hey Karen! When you do this, are you prompted to enter a username/password?

It'd also be helpful if you could include a screenshot and/or the full output that you receive when attempting to push. Thanks!

**Comment by jdmar3** [comment]
This is a known problem with known solutions. Here are a few resources:

https://stackoverflow.com/questions/29297154/github-invalid-username-or-password

https://medium.com/analytics-vidhya/github-error-remote-invalid-username-or-password-a-solution-bdf16a693f5

And here is a link to other related resources:

https://www.google.com/search?q=remote%3A+Invalid+username+or+password.+fatal%3A+Authentication+failed

**Comment by samrshi** [comment]
Hey Karen, just checking in. Have you been able to resolve this?

**Comment by karengu0** [comment]
Hi Sam! Yes, I got it resolved. Thanks for checking in!
