### ISSUE TITLE
Few Errors

### ISSUE THREAD

**Issue by Ysaid1** [comp426-2022-spring/a00#3]
Not really sure what this error is?

❌ You ran npm and it created package.json
16
::error::The output for test You ran npm and it created package.json did not match%0AExpected:%0Apackage.json%0AActual:%0ALICENSE%0AREADME.md
17
📝 You used npm to install Broswersync

**Comment by jdmar3** [comment]
I don't see any errors here: https://github.com/comp426-2022-spring/a00-Ysaid1/runs/4810198840?check_suite_focus=true

It looks like all the tests have passed.
