### ISSUE TITLE
"error  <th> is missing required "scope" attribute  element-required-attributes"

### ISSUE THREAD

**Issue by carohamunc** [comp426-2022-spring/a00#4]
When I push my final code to github, the only two error messages I receive say "error  <th> is missing required "scope" attribute  element-required-attributes." I'm not quite sure what this means but I've checked many times to make sure I copied the code from the instructions correctly and the webpage my code creates looks fine.

**Comment by camsimba** [comment]
Hey, I'll look into it. Currently, everything looks fine so I'm not sure why compiling would cause an error there. For a bit of background, \<th\> can have an optional scope in the tag that defines whether it is a part of a row or column (i.e. \<th scope="row"\>), but is only used by screen readers and has no effect upon the visual aspect of the html. Likely, there is a bug somewhere else in the code that is causing this to happen, I'll look through it and get back to you on this. If you find it before me just let me know!

**Comment by camsimba** [comment]
In the meantime, if you want to push the code without error you can change the \<th\> elements to \<th scope="col"\>. The line should look something like this: \<th scope="col"\>Column 0\</th\>\<th scope="col"\>Column 1\</th\>
Let me know if that works, and I'll see if I can't figure out why your code didn't work originally.

**Comment by carohamunc** [comment]
thank you, that worked!

**Comment by camsimba** [comment]
Cool I'll close this for now, but I may reopen it in the future as I still don't know why \<th\> error'd out without a scope.
