### ISSUE TITLE
When installing Homebrew asking for 'sudo' password?

### ISSUE THREAD

**Issue by bvalient** [comp426-2022-spring/a00#6]
I've been trying to find out what a this is and how to stop it online, however the answers seem very specific or vague (I was installing it so I could install git). I just don't know to much as to what a 'sudo' password even is. 

Here is a picture of what it looks like:

<img width="570" alt="Screen Shot 2022-01-14 at 12 01 22 PM" src="https://user-images.githubusercontent.com/69774341/149555117-46f23c33-7d61-4657-830d-e43a2b9000d0.png">

**Comment by camsimba** [comment]
Hi, let me see if I can clear some of this up. 'sudo' is added in front of a command on the CLI (command line interface) that allows whatever command to be run as the 'root' or administrator. This means that anything you run will bypass all permission restrictions and operate on the same permission level as the 'root' user. In this case, you are trying to install something that Ubuntu (or whatever you are using) is not sure should be allowed. So, it is asking for administrator permissions to install it. The password should be whatever password you use to log in to the CLI or computer. Let me know if you're still confused and we can work on it a little more. Just @ me in this thread and I'll see it and respond!

**Comment by bvalient** [comment]
Sounds good! Fixed it all up.
