### ISSUE TITLE
Issue Pushing to GitHub

### ISSUE THREAD

**Issue by jcsansom-cyber** [comp426-2022-spring/a00#7]
Hi there! So originally I had an issue with my GitHub Token, and couldn't push, but I updated it and now I am getting this issue:
Sync Changes: Failed to run 'git fetch'. remote: Repository not found. fatal: repository 'https://github.com/jcsansom-cyber/comp426-2022-spring.git/' not found

I have no idea how to fix this.

**Comment by camsimba** [comment]
Hey, I think I can clear this up real quick! So, your link is not the one that you should be pushing to. The one you have listed in this issue thread is 'https://github.com/jcsansom-cyber/comp426-2022-spring.git/' but you should be pushing to 'https://github.com/comp426-2022-spring/a00-jcsansom-cyber.git'. The one you have listed is mixed around a little bit, try targeting the link I listed for a fetch and let me know what it says!

**Comment by camsimba** [comment]
Just wanted to check back in and make sure everything is working. Let me know if you need any more help or if you fixed it!

**Comment by jcsansom-cyber** [comment]
Yes, this did help me! I recloned the assignment and it ended up working! Thanks for the help and sorry I didn't respond at the time.

**Comment by camsimba** [comment]
It's alright, glad you were able to figure it out!
